PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterm: <http://purl.org/dc/terms/>
CONSTRUCT {
    ?s <http://w3id.org/sepses/vocab/ref/attack#implementsTechnique> ?te.
    ?s <http://w3id.org/sepses/vocab/ref/attack#hasReference> ?r .
    ?te <http://w3id.org/sepses/vocab/ref/attack#accomplishesTactic> ?t.
    ?r <http://w3id.org/sepses/vocab/ref/icsa#hasCVE> ?cve .
    ?cve<http://w3id.org/sepses/vocab/ref/cve#hasCPE> ?cpe .
    ?r <http://w3id.org/sepses/vocab/ref/icsa#hasCWE> ?cwe .
    ?cwe <http://w3id.org/sepses/vocab/ref/cwe#hasCAPEC> ?capec.
    ?s <http://w3id.org/sepses/vocab/ref/attack#hasGroup> ?g.
    ?cpe <http://w3id.org/sepses/vocab/ref/cpe#hasProduct> ?pro.
    	?cpe <http://w3id.org/sepses/vocab/ref/cpe#hasVendor> ?ven.
} WHERE {
    ?s a <http://w3id.org/sepses/vocab/ref/attack#Malware>.
    ?s <http://w3id.org/sepses/vocab/ref/attack#implementsTechnique> ?te .
    OPTIONAL {?s<http://w3id.org/sepses/vocab/ref/attack#hasReference> ?r .
    ?r <http://w3id.org/sepses/vocab/ref/icsa#hasCVE> ?cve .
        ?r <http://w3id.org/sepses/vocab/ref/icsa#hasCWE> ?cwe .
        ?cwe <http://w3id.org/sepses/vocab/ref/cwe#hasCAPEC> ?capec.
        ?cve <http://w3id.org/sepses/vocab/ref/cve#hasCPE> ?cpe.
    	?cpe <http://w3id.org/sepses/vocab/ref/cpe#hasProduct> ?pro.
    	?cpe <http://w3id.org/sepses/vocab/ref/cpe#hasVendor> ?ven}
    ?te <http://w3id.org/sepses/vocab/ref/attack#accomplishesTactic> ?t.
        ?s <http://w3id.org/sepses/vocab/ref/attack#hasGroup> ?g.

    ?s dcterm:title "Triton"
    
}